-- ----------------------------
-- 增加第三方认证配置
-- ----------------------------
UPDATE "BLADEX"."BLADE_CLIENT" set AUTHORIZED_GRANT_TYPES = 'refresh_token,password,authorization_code,captcha,social';

-- ----------------------------
-- 创建用户第三方认证表
-- ----------------------------
CREATE TABLE "BLADEX"."BLADE_USER_OAUTH" (
    "ID" NUMBER(20) NOT NULL ,
    "TENANT_ID" NVARCHAR2(12) ,
    "USER_ID" NUMBER(20) ,
    "USERNAME" VARCHAR2(32) ,
    "NICKNAME" VARCHAR2(64) ,
    "AVATAR" VARCHAR2(1000),
    "BLOG" VARCHAR2(50) ,
    "COMPANY" VARCHAR2(255) ,
    "LOCATION" VARCHAR2(255) ,
    "EMAIL" VARCHAR2(255) ,
    "REMARK" VARCHAR2(255) ,
    "GENDER" VARCHAR2(16) ,
    "SOURCE" VARCHAR2(16) ,
    PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."ID" IS '主键';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."TENANT_ID" IS '租户ID';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."USER_ID" IS '用户主键';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."USERNAME" IS '账号';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."NICKNAME" IS '用户名';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."AVATAR" IS '头像';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."BLOG" IS '应用主页';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."COMPANY" IS '公司名';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."LOCATION" IS '地址';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."EMAIL" IS '邮件';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."REMARK" IS '备注';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."GENDER" IS '性别';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."SOURCE" IS '来源';
COMMENT ON TABLE "BLADEX"."BLADE_USER_OAUTH" IS '用户第三方认证表';
