ALTER TABLE "BLADEX"."BLADE_LOG_ERROR"
    ADD ("REMOTE_IP" VARCHAR2(255) );

COMMENT ON COLUMN "BLADEX"."BLADE_LOG_ERROR"."REMOTE_IP" IS '操作IP地址';


ALTER TABLE "BLADEX"."BLADE_LOG_USUAL"
    ADD ("REMOTE_IP" VARCHAR2(255) )
    ADD ("METHOD_CLASS" VARCHAR2(255) )
    ADD ("METHOD_NAME" VARCHAR2(255) );

COMMENT ON COLUMN "BLADEX"."BLADE_LOG_ERROR"."REMOTE_IP" IS '操作IP地址';
COMMENT ON COLUMN "BLADEX"."BLADE_LOG_ERROR"."METHOD_CLASS" IS '方法类';
COMMENT ON COLUMN "BLADEX"."BLADE_LOG_ERROR"."METHOD_NAME" IS '方法名';
